"""create_templates_table

Revision ID: 2932098a1c51
Revises: c3b199c4a6ec
Create Date: 2026-01-25 18:01:58.940302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2932098a1c51'
down_revision: Union[str, Sequence[str], None] = 'c3b199c4a6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=False),
    sa.Column('supports_accent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_resumes_template_id_templates', 'templates', ['template_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_resumes_template_id_templates', type_='foreignkey')

    op.drop_table('templates')
    # ### end Alembic commands ###
