"""update custom section models

Revision ID: b03c3aa972a0
Revises: bf443b580f36
Create Date: 2026-01-26 07:47:43.818971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03c3aa972a0'
down_revision: Union[str, Sequence[str], None] = 'bf443b580f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_section_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.JSON(), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('description')
        batch_op.drop_column('location')
        batch_op.drop_column('date')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_custom', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('schema', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('schema')
        batch_op.drop_column('is_custom')

    with op.batch_alter_table('custom_section_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
