"""remove default tone and length from cover letter templates

Revision ID: b23f8014bfd3
Revises: 7c02001cfc23
Create Date: 2026-02-08 14:37:39.907107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23f8014bfd3'
down_revision: Union[str, Sequence[str], None] = '7c02001cfc23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover_letter_templates', schema=None) as batch_op:
        batch_op.drop_column('default_length')
        batch_op.drop_column('default_tone')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover_letter_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_tone', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('default_length', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
