"""create settings table

Revision ID: d3805942e150
Revises: 9756a5b5c215
Create Date: 2026-01-28 09:42:44.012380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3805942e150'
down_revision: Union[str, Sequence[str], None] = '9756a5b5c215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic
    op.create_table(
        'settings',
        sa.Column('key', sa.String(length=128), nullable=False),
        sa.Column('value', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic
    op.drop_table('settings')
    # ### end Alembic commands ###
